<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(HOME)/.config/r2modmanPlus-local/WordPlay/profiles/Default/BepInEx/core/BepInEx*.dll" />
    <Reference Include="$(HOME)/.config/r2modmanPlus-local/WordPlay/profiles/Default/BepInEx/core/0Harmony.dll" />
    <Reference Include="$(HOME)/.steam/steam/steamapps/common/Word Play/Word Play_Data/Managed/Unity*.dll" />
    <Reference Include="$(HOME)/.steam/steam/steamapps/common/Word Play/Word Play_Data/Managed/Assembly*.dll" />
    <EmbeddedResource Include="Assets/*.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
  </ItemGroup>
  
  <Target Name="AutoCopyPlugin" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)/Archipelago.MultiClient.Net.dll" DestinationFolder="$(HOME)/.config/r2modmanPlus-local/WordPlay/profiles/Default/BepInEx/plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(HOME)/.config/r2modmanPlus-local/WordPlay/profiles/Default/BepInEx/plugins" />
  </Target>
</Project>
